name: npsg_store
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #gRPC

  #firebase
  protobuf: ^2.0.0
  grpc: ^3.0.0

  #state management
  flutter_hooks: ^0.15.0
  flutter_riverpod: ^0.13.1+1

  #fonts
  google_fonts: ^2.0.0
  
  #icons
  cupertino_icons: ^1.0.2

  #navigation
  fluro: ^2.0.3

  #widgets
  carousel_pro: ^1.0.0
  protoc_plugin: ^20.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


